/* Generated by Yosys 0.12 (git sha1 UNKNOWN, gcc 11.1.0 -march=x86-64 -mtune=generic -O2 -fno-plt -fPIC -Os) */

module DSPBlock_6x6_F400_uid35(clk, X, Y, R);
  wire [11:0] _0_;
  output [11:0] R;
  input [5:0] X;
  input [5:0] Y;
  input clk;
  wire [11:0] m;
  wire [11:0] mint;
  wire [11:0] rtmp;
  assign _0_ = $signed({ 6'h00, X }) * $signed({ 6'h00, Y });
  assign mint = _0_;
  assign m = mint;
  assign rtmp = m;
  assign R = rtmp;
endmodule
