/* Generated by Yosys 0.12 (git sha1 UNKNOWN, gcc 11.1.0 -march=x86-64 -mtune=generic -O2 -fno-plt -fPIC -Os) */

module SystolicArrayKernel(clk, rst, rowsA, colsB, SOB, EOB, colsC, EOB_Q_o);
  wire [11:0] _00_;
  wire [32:0] _01_;
  wire [11:0] _02_;
  wire [11:0] _03_;
  wire _04_;
  wire _05_;
  wire [32:0] _06_;
  wire [11:0] _07_;
  wire [11:0] _08_;
  wire _09_;
  wire _10_;
  wire [11:0] _11_;
  wire [32:0] _12_;
  wire [11:0] _13_;
  wire [11:0] _14_;
  wire _15_;
  wire _16_;
  wire [32:0] _17_;
  wire [11:0] _18_;
  wire [11:0] _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire [32:0] _23_;
  wire [11:0] _24_;
  wire [11:0] _25_;
  wire _26_;
  wire _27_;
  wire [32:0] _28_;
  wire [11:0] _29_;
  wire [11:0] _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire [32:0] _34_;
  wire [11:0] _35_;
  wire [11:0] _36_;
  wire _37_;
  wire _38_;
  wire [32:0] _39_;
  wire [32:0] _40_;
  wire [11:0] _41_;
  wire [11:0] _42_;
  wire _43_;
  wire _44_;
  input EOB;
  output EOB_Q_o;
  input SOB;
  input clk;
  input [35:0] colsB;
  output [98:0] colsC;
  input [35:0] rowsA;
  input rst;
  wire [395:0] systolic_c_out_2d;
  wire [11:0] systolic_eob_2d;
  wire [11:0] systolic_sob_2d;
  wire [143:0] systolic_wires_cols_2d;
  wire [143:0] systolic_wires_rows_2d;
  PE_S3 \rows:1.cols:1.pe_ij  (
    .C_out(systolic_c_out_2d[32:0]),
    .C_out_Q(_40_),
    .EOB(systolic_eob_2d[0]),
    .EOB_Q(_33_),
    .SOB(systolic_sob_2d[0]),
    .SOB_Q(_22_),
    .clk(clk),
    .rst(rst),
    .s3_col_j_B(systolic_wires_cols_2d[11:0]),
    .s3_col_jm1_B(_11_),
    .s3_row_i_A(systolic_wires_rows_2d[11:0]),
    .s3_row_im1_A(_00_)
  );
  PE_S3 \rows:1.cols:2.pe_ij  (
    .C_out(systolic_c_out_2d[65:33]),
    .C_out_Q(_01_),
    .EOB(systolic_eob_2d[1]),
    .EOB_Q(_44_),
    .SOB(systolic_sob_2d[1]),
    .SOB_Q(_43_),
    .clk(clk),
    .rst(rst),
    .s3_col_j_B(systolic_wires_cols_2d[23:12]),
    .s3_col_jm1_B(_42_),
    .s3_row_i_A(systolic_wires_rows_2d[23:12]),
    .s3_row_im1_A(_41_)
  );
  PE_S3 \rows:1.cols:3.pe_ij  (
    .C_out(systolic_c_out_2d[98:66]),
    .C_out_Q(_06_),
    .EOB(systolic_eob_2d[2]),
    .EOB_Q(_05_),
    .SOB(systolic_sob_2d[2]),
    .SOB_Q(_04_),
    .clk(clk),
    .rst(rst),
    .s3_col_j_B(systolic_wires_cols_2d[35:24]),
    .s3_col_jm1_B(_03_),
    .s3_row_i_A(systolic_wires_rows_2d[35:24]),
    .s3_row_im1_A(_02_)
  );
  PE_S3 \rows:2.cols:1.pe_ij  (
    .C_out(systolic_c_out_2d[131:99]),
    .C_out_Q(_12_),
    .EOB(systolic_eob_2d[3]),
    .EOB_Q(_10_),
    .SOB(systolic_sob_2d[3]),
    .SOB_Q(_09_),
    .clk(clk),
    .rst(rst),
    .s3_col_j_B(systolic_wires_cols_2d[47:36]),
    .s3_col_jm1_B(_08_),
    .s3_row_i_A(systolic_wires_rows_2d[59:48]),
    .s3_row_im1_A(_07_)
  );
  PE_S3 \rows:2.cols:2.pe_ij  (
    .C_out(systolic_c_out_2d[164:132]),
    .C_out_Q(_17_),
    .EOB(systolic_eob_2d[4]),
    .EOB_Q(_16_),
    .SOB(systolic_sob_2d[4]),
    .SOB_Q(_15_),
    .clk(clk),
    .rst(rst),
    .s3_col_j_B(systolic_wires_cols_2d[59:48]),
    .s3_col_jm1_B(_14_),
    .s3_row_i_A(systolic_wires_rows_2d[71:60]),
    .s3_row_im1_A(_13_)
  );
  PE_S3 \rows:2.cols:3.pe_ij  (
    .C_out(systolic_c_out_2d[197:165]),
    .C_out_Q(_23_),
    .EOB(systolic_eob_2d[5]),
    .EOB_Q(_21_),
    .SOB(systolic_sob_2d[5]),
    .SOB_Q(_20_),
    .clk(clk),
    .rst(rst),
    .s3_col_j_B(systolic_wires_cols_2d[71:60]),
    .s3_col_jm1_B(_19_),
    .s3_row_i_A(systolic_wires_rows_2d[83:72]),
    .s3_row_im1_A(_18_)
  );
  PE_S3 \rows:3.cols:1.pe_ij  (
    .C_out(systolic_c_out_2d[230:198]),
    .C_out_Q(_28_),
    .EOB(systolic_eob_2d[6]),
    .EOB_Q(_27_),
    .SOB(systolic_sob_2d[6]),
    .SOB_Q(_26_),
    .clk(clk),
    .rst(rst),
    .s3_col_j_B(systolic_wires_cols_2d[83:72]),
    .s3_col_jm1_B(_25_),
    .s3_row_i_A(systolic_wires_rows_2d[107:96]),
    .s3_row_im1_A(_24_)
  );
  PE_S3 \rows:3.cols:2.pe_ij  (
    .C_out(systolic_c_out_2d[263:231]),
    .C_out_Q(_34_),
    .EOB(systolic_eob_2d[7]),
    .EOB_Q(_32_),
    .SOB(systolic_sob_2d[7]),
    .SOB_Q(_31_),
    .clk(clk),
    .rst(rst),
    .s3_col_j_B(systolic_wires_cols_2d[95:84]),
    .s3_col_jm1_B(_30_),
    .s3_row_i_A(systolic_wires_rows_2d[119:108]),
    .s3_row_im1_A(_29_)
  );
  PE_S3 \rows:3.cols:3.pe_ij  (
    .C_out(systolic_c_out_2d[296:264]),
    .C_out_Q(_39_),
    .EOB(systolic_eob_2d[8]),
    .EOB_Q(_38_),
    .SOB(systolic_sob_2d[8]),
    .SOB_Q(_37_),
    .clk(clk),
    .rst(rst),
    .s3_col_j_B(systolic_wires_cols_2d[107:96]),
    .s3_col_jm1_B(_36_),
    .s3_row_i_A(systolic_wires_rows_2d[131:120]),
    .s3_row_im1_A(_35_)
  );
  assign systolic_wires_rows_2d = { _35_, _29_, _24_, rowsA[35:24], _18_, _13_, _07_, rowsA[23:12], _02_, _41_, _00_, rowsA[11:0] };
  assign systolic_wires_cols_2d = { _36_, _30_, _25_, _19_, _14_, _08_, _03_, _42_, _11_, colsB };
  assign systolic_sob_2d = { _37_, _31_, _26_, _20_, _15_, _09_, _04_, _43_, _22_, systolic_sob_2d[4:3], SOB };
  assign systolic_eob_2d = { _38_, _32_, _27_, _21_, _16_, _10_, _05_, _44_, _33_, systolic_eob_2d[4:3], EOB };
  assign systolic_c_out_2d = { _39_, _34_, _28_, _23_, _17_, _12_, _06_, _01_, _40_, 99'h0000000000000000000000000 };
  assign colsC = systolic_c_out_2d[395:297];
  assign EOB_Q_o = systolic_eob_2d[11];
endmodule
